package com.wyre.sushi;

public enum TokenType {
    //single char tokens
    LEFT_PAREN,RIGHT_PAREN,LEFT_BRACE,RIGHT_BRACE,COMMA,DOT,PLUS,MINUS,SEMICOLON,SLASH,STAR,

    //one to two char tokens
    BANG,BANG_EQUAL,EQUAL,EQUAL_EQUAL,GREATER,GREATER_EQUAL,LESS,LESS_EQUAL,

    //Literals
    IDENTIFIER,STRING,NUMBER,

    //Keywords
    AND,CLASS,FUN,ELSE,FALSE,FOR,IF,NIL,OR,PRINT,RETURN,SUPER,THIS,TRUE,VAR,WHILE,EOF
}
